# Generated by Django 5.0.1 on 2024-07-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0003_alter_blog_content_alter_blog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, default='published', max_length=20, null=True),
        ),
    ]
