# Generated by Django 5.0.1 on 2024-07-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0005_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='speciality',
            field=models.CharField(blank=True, default='Surgeon', max_length=200, null=True),
        ),
    ]
