# Generated by Django 5.0.1 on 2024-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0006_profile_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='speciality',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
