# Generated by Django 5.0.1 on 2024-07-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0007_alter_profile_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='', max_length=255)),
                ('patient_name', models.CharField(default='', max_length=255)),
                ('slot_booked_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('start_time', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('end_time', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
