# Generated by Django 5.0.1 on 2024-07-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0008_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student')], default='Student', max_length=255)),
                ('name', models.CharField(default='', max_length=244)),
                ('enrollment', models.CharField(default='', max_length=255)),
                ('resume', models.ImageField(blank=True, upload_to='static/')),
                ('profile_picture', models.ImageField(blank=True, upload_to='static/')),
                ('email', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('tenth_grade', models.CharField(default='', max_length=10)),
                ('twelth_grade', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
