# Generated by Django 5.0.1 on 2024-07-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0009_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=244)),
                ('resume', models.ImageField(blank=True, upload_to='static/')),
                ('profile_picture', models.ImageField(blank=True, upload_to='static/')),
                ('email', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('tenth_grade', models.CharField(blank=True, default='', max_length=10)),
                ('twelth_grade', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='user_type',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registerapp.student')),
            ],
        ),
    ]
