# Generated by Django 5.0.1 on 2024-07-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0010_student_remove_students_user_type_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
