# Generated by Django 5.0.1 on 2024-07-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0012_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(blank=True, default='', max_length=244),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
