# Generated by Django 5.0.1 on 2024-07-21 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0013_admin_email_admin_name_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='enrollment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registerapp.student'),
        ),
    ]
