# Generated by Django 5.0.1 on 2024-07-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0014_alter_admin_enrollment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='', max_length=244)),
                ('time', models.CharField(blank=True, default='', max_length=244)),
                ('location', models.CharField(blank=True, default='', max_length=244)),
                ('company', models.CharField(blank=True, default='', max_length=244)),
                ('job_roles', models.CharField(blank=True, default='', max_length=244)),
                ('details', models.CharField(blank=True, default='', max_length=244)),
            ],
        ),
    ]
