# Generated by Django 5.0.1 on 2024-07-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0015_placementdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdrive',
            name='details',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
