# Generated by Django 5.0.1 on 2024-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0016_alter_placementdrive_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
