# Generated by Django 5.0.1 on 2024-07-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registerapp', '0017_admin_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='applied',
            field=models.CharField(blank=True, default='no', max_length=200, null=True),
        ),
    ]
